# Subliminal
#
# Version 0.1
FROM wbvreeuwijk/nzb-base:latest
MAINTAINER Bas van Reeuwijk <bas@reeuwijk.net>

LABEL Description="This image will install a Subliminal command environment" Version="1.0"

RUN pip install subliminal

VOLUME ["/video"]

CMD ["/bin/bash"]




